package com.mhsoft.mhagro;


import ca.weblite.codename1.json.JSONException;
import ca.weblite.codename1.json.JSONObject;
import com.codename1.capture.Capture;
import com.codename1.components.FloatingActionButton;
import com.codename1.components.SpanLabel;
import com.codename1.components.ToastBar;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.messaging.Message;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.EncodedImage;
import com.codename1.ui.FontImage;
import com.codename1.ui.Image;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.spinner.Picker;
import com.codename1.ui.validation.LengthConstraint;
import com.codename1.ui.validation.RegexConstraint;
import com.codename1.ui.validation.Validator;
import java.util.Map;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MHAgro {

    private Form current;
    private Resources theme;
    private static final String appName = "MHAgri" ;
    private String productImagePath  ;
    private static final String Phone = "Appelez-nous";
    private static final String Email = "Envoyez-nous un email";
    private static final String PhoneNumber = "+237699185307";
    private static final String EmailValue= "mhagro@gmail.com";
    
    private static final String ip = "http://localhost:8080/";
//  private static final String ip = "http://192.168.43.64:8080/";
//  private static final String ip = "http://10.20.3.160:8080/";
//  private static final String ip = "http://10.20.6.160:8080/";
//  private static final String ip = "http://10.20.7.160:8080/";
//    private static final String ip = "http://192.168.7.1:8080/";



    private EncodedImage Placeholder;
    private Vendeur vendeur ;


    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
        
        Image tmp = Image.createImage(Display.getInstance().getDisplayWidth(), Display.getInstance().getDisplayWidth() / 4 * 3, 0);
        Placeholder = EncodedImage.createFromImage(tmp, false);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
//        myproductlistForm();
        marcheForm();
       
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }
   void addMenu(Form form){
        Container c = new Container(new BorderLayout());
        Container layoutY = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        Label appname = new Label(appName);
        appname.setUIID("SplashScreenAppNameLabel");
        layoutY.add(appname);
        c.add(BorderLayout.CENTER,BorderLayout.centerAbsolute(layoutY));
        form.getToolbar().addComponentToSideMenu(c);
        form.getToolbar().addMaterialCommandToSideMenu("Profile", FontImage.MATERIAL_PERSON, e -> {editproducteurForm(vendeur);});
        form.getToolbar().addMaterialCommandToSideMenu("Mes produits", FontImage.MATERIAL_LIST, e -> {myproductlistForm(vendeur);});
        form.getToolbar().addMaterialCommandToSideMenu("Deconnection", FontImage.MATERIAL_EXIT_TO_APP, e -> { marcheForm();});
    }
   
   void addMenuClient(Form form){
        Container c = new Container(new BorderLayout());
        Container layoutY = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        Label appname = new Label(appName);
        appname.setUIID("SplashScreenAppNameLabel");
        layoutY.add(appname);
        c.add(BorderLayout.CENTER,BorderLayout.centerAbsolute(layoutY));
        form.getToolbar().addComponentToSideMenu(c);
        form.getToolbar().addMaterialCommandToSideMenu("Le marché", FontImage.MATERIAL_STORE, e -> {marcheForm();});
        form.getToolbar().addMaterialCommandToSideMenu("Producteurs", FontImage.MATERIAL_PEOPLE, e -> {producteursForm();});
        form.getToolbar().addMaterialCommandToSideMenu("A propos", FontImage.MATERIAL_INFO_OUTLINE, e -> {showaproposscreen();});
        form.getToolbar().addMaterialCommandToSideMenu("Support", FontImage.MATERIAL_HELP_OUTLINE, e -> {showsupportscreen();});
    }
    
   public void myproductlistForm(Vendeur vendeur){
        Form myproductlistform = new Form("Mes Produits",new BorderLayout());
        addMenu(myproductlistform);
        
        VendeurProductInfiniteContainer pic = new VendeurProductInfiniteContainer();
        myproductlistform.addComponent(BorderLayout.CENTER,pic.getProduct(ip,vendeur.getId(),Placeholder,vendeur));
        
        FloatingActionButton fab = FloatingActionButton.createFAB(FontImage.MATERIAL_ADD);
        fab.addActionListener(e -> createproductForm(myproductlistform));
        fab.bindFabToContainer(myproductlistform.getContentPane());
        
        myproductlistform.show();
    }
   
   public void createproductForm(Form form){
       Form createproductform = new Form("Add Product",new BoxLayout(BoxLayout.Y_AXIS));
      
       createproductform.getToolbar().setBackCommand(new Command(""){
                              public void actionPerformed(ActionEvent evt){
                                form.showBack();
                                
                            }
                     });
       
       Label productImageLabel = new Label("Image Produit","ProductCreateLabel");
       Button productImage = new Button();
       Image defaultAvatar = FontImage.createMaterial(FontImage.MATERIAL_ADD_A_PHOTO, "InputAvatarImage", 8);
       productImage.setIcon(defaultAvatar);
       productImage.setUIID("ProductImage");
       
       Label  productTitleLabel = new Label("Intitule Produit","ProductCreateLabel");
       TextField productTitle = new TextField();
       productTitle.setHint("Exples: Macabo,tomate,mais");
       
       Label productPriceLabel = new Label("Prix unitaire produit","ProductCreateLabel");
       TextField productPrice = new TextField();
       productPrice.setConstraint(TextArea.NUMERIC);
       productPrice.setHint("Exples: 1000,2000,5000");

       
       Label productUnitySaleLabel = new Label("Unite de vente produit","ProductCreateLabel");
       TextField productUnitySale = new TextField();
       productUnitySale.setHint("Exples: Kg,litre");
       
       Label productCategoryLabel = new Label("Categorie produit","ProductCreateLabel");
       Picker productCategory = new Picker();
       productCategory.setStrings("Fruits","Legumes","Tubercules","Cereales");
       productCategory.setSelectedString(" ");
       
       Label productTotalQuantityLabel = new Label("Quantite totale stock produit","ProductCreateLabel");
       TextField productTotalQuantity = new TextField();
       productTotalQuantity.setHint("Exples: 25sacs,10tonnes,300poulets");


       
       Label productDescriptionLabel = new Label("Description produit","ProductCreateLabel");
       TextArea productDescription = new TextArea(5,Display.getInstance().getDisplayWidth()-3);
       
       Label productOnlineLabel = new Label("Publier le produit","ProductCreateLabel");
       Picker productOnline = new Picker();
       productOnline.setStrings("Oui","Non");
       productOnline.setSelectedString("Oui");

       productImagePath = null ;
       
       Button saveProductButton = new Button("Enregistrer");
       
       productImage.addActionListener((evt)->{
           if(Dialog.show("Appareil photo ou gallerie","Voulez-vous utiliser l'appareil photo ou la gallerie", "Appareil photo", "Gallerie")){
            productImagePath    = Capture.capturePhoto(1024, -1);
                if(productImagePath == null){
                    return ;
                }
               if(productImagePath != null){
                try{
//             Image img = Image.createImage(productImagePath).scaledSmallerRatio(256,256);
               Image img = Image.createImage(productImagePath).fill(256,256);
               productImage.setIcon(img);
               createproductform.revalidate();
           }catch(IOException ex){
               Log.p("Erreur Photo"+ex,Log.ERROR);
               return ;
           }
           }
           }else {
                openGallery(ee -> {
                    productImagePath = (String)ee.getSource() ;
                    if(productImagePath !=  null) {
                        try {
                            Image img = Image.createImage(productImagePath).fill(256,256);
                            productImage.setIcon(img);
                            createproductform.revalidate();
                            } catch(IOException err) {
                            ToastBar.showErrorMessage("An error occured while loading the image: " + err);
                            Log.e(err);
                        }
                    }
                }, GALLERY_IMAGE);
            }
          
          
       } );
        
        
        saveProductButton.addActionListener(e -> {
            if(productImagePath ==  null){
                Dialog.show("Erreur","selection image du produit","OK",null);
            }else{
                if(productCategory.getSelectedString() == " "){
                 Dialog.show("Error","selection categorie produit","OK",null);
                }else{
                    String action = "create";
                    ProductClient productclient = new ProductClient(ip);
                    Product product = new Product();
                    product.setImage(productImagePath);
                    product.setIntitule(productTitle.getText());
                    product.setPrix_unitaire(productPrice.getText());
                    product.setUnite_de_vente(productUnitySale.getText());
                    product.setCategorie(productCategory.getSelectedString());
                    product.setQuantite_stock(productTotalQuantity.getText());
                    product.setDescription(productDescription.getText());
                    product.setPublier(productOnline.getText());
                    productclient.sendRequest(action,product,null,vendeur.getId());
                    Dialog.show("Info","enregistrer avec succes","OK",null);
                }
            }
            
            });
        
        
        
       
       createproductform.add(productImageLabel);
       createproductform.add(productImage);
       createproductform.add(productTitleLabel);
       createproductform.add(productTitle);
       createproductform.add(productPriceLabel);
       createproductform.add(productPrice);
       createproductform.add(productUnitySaleLabel);
       createproductform.add(productUnitySale);
       createproductform.add(productCategoryLabel);
       createproductform.add(productCategory);
       createproductform.add(productTotalQuantityLabel);
       createproductform.add(productTotalQuantity);
       createproductform.add(productDescriptionLabel);
       createproductform.add(productDescription);
       createproductform.add(productOnlineLabel);
       createproductform.add(productOnline);
       createproductform.add(saveProductButton);
       
       Validator validator = new Validator();
                  validator.setShowErrorMessageForFocusedComponent(true);
                  validator.setValidationFailureHighlightMode(Validator.HighlightMode.UIID_AND_EMBLEM);
                  validator.setErrorMessageUIID("ProductValidationLabel");
                  
        validator.addConstraint(productTitle,new LengthConstraint(1,"Saisir intitule produit")).
                  addConstraint(productPrice,new LengthConstraint(1,"Saisir prix du produit")). 
                  addConstraint(productUnitySale,new LengthConstraint(1,"Saisir unite de vente du produit")). 
                  addConstraint(productDescription,new LengthConstraint(1,"Saisir la description du produit")). 
                  addConstraint(productTotalQuantity, new LengthConstraint(1,"Saisir quantite total en stock du produit"));               
        validator.addSubmitButtons(saveProductButton);
       createproductform.show();
   }
   
   public void marcheForm(){
       Form marcheform = new Form("Le marché",new BorderLayout());
       addMenuClient(marcheform);
       
       Style s = UIManager.getInstance().getComponentStyle("Label");
       FontImage searchIcon = FontImage.createMaterial(FontImage.MATERIAL_SEARCH, s); 
        
       marcheform.getToolbar().addCommandToOverflowMenu(new Command("Par categorie",searchIcon){
            public void actionPerformed(ActionEvent evt){
                Container container = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                Picker productCategory = new Picker();
                productCategory.setStrings("Fruits","Legumes","Tubercules","Cereales");
                productCategory.setSelectedString("Fruits");
                Button b = new Button("Recherche");
                b.addActionListener(e -> {
                      String resource = "parcategorie/0/10/Oui/"+productCategory.getSelectedString();
                      rechercheForm(marcheform,resource);
                
                    });
                container.add(productCategory);
                container.add(b);
                Dialog.show("Recherche",container ,new Command("Annuler"));  
                
            }});
       
       marcheform.getToolbar().addCommandToOverflowMenu(new Command("Par ville",searchIcon){
            public void actionPerformed(ActionEvent evt){
                Container container = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                Picker ville = new Picker();
                ville.setStrings("Ngaoundere","Belel","Mbe","Nganha","Nyambaka","Martap",
                              "Tignere","Mayo-Baleo","Kontcha",
                              "Banyo","Bankim","Mayo-Darle",
                              "Meiganga","Dir","Djohong","Ngaoui",
                              "Tibati","Ngaoundal",
                              "Nanga-Eboko","Bibey","Lembe","Mbandjock","Minta","Nkoteng","Sem",
                              "Monatele","Batchenga","Ebebda","Elig-Mfomo","Evodoula","Lobo","Monatele","Obala","Okola","Saa",
                              "Bafia","Bokito","Deuk","Kiiki","Kom-Yambetta","Makenene","Nitoukou","Ombessa",
                              "Ntui","Mbangassina","Ngambe-Tikar","Ngoro","Yoko",
                              "Mfou","Awae","Esse",
                              "Ngoumou","Akono","Bokok","Mbankomo",
                              "Yaounde",
                              "Eseka","Biyouha","Bot-Makak","Mbandjock","Dibang","Makak","Matomb","Messondo","Ngog-Mapubi","Nguibassal",
                              "Akonolinga","Ayos","Endom",
                              "Mbalmayo","Akoeman","Dzeng","Mengueme","Ngomedzap","Nkolmetet",
                              "Yokadouma","Gari-Gombo","Moloundou","Salapoumbe",
                              "Abong-mbang","Bebeng","Mbouanz","Dja","Dimako","Dimako","Doume","Doumaintang","Lomie","Messok","Messamena","Somalomo","Ngoyla","Nguelemendouka","Mboma",
                              "Batouri","Kette","Mbang","Ndelele",
                              "Bertoua","Belabo","Betare-Oya","Diang","Garoua-Boulai","Mandjou","Ngoura",
                              "Maroua","Bogo","Gazawa","Meri","Pette","Ndoukoula","Dargala",
                              "Kousseri","Blangoua","Darak","Fotokol","Goulfrey","Hile-Alifa","Logone-Birni","Makary","Waza","Zina",
                              "Yagoua","Datcheka","Gobo","Gueme","Guere","Kai-Kai","Kalfou","Kay-Hay","Maga","Tchati-Bali","Wina",
                              "Kaele","Guidiguis","Mindif","Meri","Moutourwa","Moulvoudaye","Pohri","Taibong",
                              "Mora","Kolofota","Tokombere",
                              "Mokolo","Bourrha","Hina","Koza","Mogode","Mayo-Maskota","Soulede-Roua",
                              "Nkongsamba","Bare-Bakem","Bonalea","Dibombari","Loum","Manjo","Mbanga","Melong","Njombe","Penja","Njongo","Nlonako",
                              "Yabassi","Nkondjock","Yingui","Nord-Makombe",
                              "Edea","Dizangue","Dibamba","Massok-Songloulou","Mouanko","Ndom","Ngambe","Ngwei","Nyanon","Pouma",
                              "Douala",
                              "Garoua","Bibemi","Dembo","Lagdo","Mayo-Hourra","Pitoa","Tcheboa","Demsa","Bascheo",
                              "Poli","Beka",
                              "Guider","Figuil","Mayo-Oulo",
                              "Tcholire","Rey-Bouba","Touboro",
                              "Fundong","Belo","Bum","Njinikom",
                              "Kumbo","Jakiri","Mbven","Nkum","Noni","Oku",
                              "Nkambe","Ako","Misaje","Ndu","Nwa",
                              "Wum","FunGom","Furu-Awa","Menchum-Valley",
                              "Bamenda","Bafut","Bali","Santa-Akum","Tuboro",
                              "Mbengwi","Batibo","Njikwa","Angie","Widikum-Menka",
                              "Ndop","Babessi","Bali-Kumbat",
                              "Mbouda","Babadjou","Batcham","Galim",
                              "Bafang","Bafou","Bana","Bafang","Bandja","Banka","Kekem","Banwa",
                              "Baham","Bamendjou","Bangou","Batie",
                              "Bandjoun","Bayagam","Poumougne",
                              "Dschang","Fokoue","Fongo-Tongo","Nkong-Ni","Penka-Michel","Santchou",
                              "Bafoussam","Baleng","Bamougoum",
                              "Bangante","Bazou","Bassamba","Tonga",
                              "Foumba","Bangourain","Foumbot","Kouoptamo","Koutaba","Magba","Malentouen","Massangam","Njimom",
                              "Sangmelima","Bengbis","Djoum","Meyomessala","Meyomessi","Mintom","Oveng","Sangmelima","Zoetele",
                              "Ebolowa","Biwong-Bane","Biwong-Bulu","Efoulan","Mengong","Mvangane","Ngoulemakong",
                              "Kribi","Akom-II","Bipindi","Campo","Niete","Lokundje","Lolodorf","Mvengue",
                              "Ambam","MAAN","Olamze","Kye-Ossi",
                              "Limbe","Buea","Muyuka","Tiko",
                              "Bangem","Tombel","Nguti",
                              "Menji","Alou","Fontem","Wabane",
                              "Mamfe","Akwaya","Eyumodjock","Upper-Bayang",
                              "Kumba","Konye","Mbongue",
                              "Mudemba","Bamuso","Ekondo-Titi","Idabato","Isanguele","Kombo-Abedimo","Kombo-Idinti","Mudemba");
                ville.setSelectedString("Yaounde");
                Button b = new Button("Recherche");
                b.addActionListener(e -> {
                      String resource = "parville/0/10/Oui/"+ville.getSelectedString();
                      rechercheForm(marcheform,resource);
                
                    });
                container.add(ville);
                container.add(b);
                Dialog.show("Recherche",container ,new Command("Annuler"));  
                
            }});
        
         marcheform.getToolbar().addCommandToOverflowMenu(new Command("Par Intitule",searchIcon){
            public void actionPerformed(ActionEvent evt){
                Container container = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                TextField intitule = new TextField();
                Button b = new Button("Recherche");
                b.addActionListener(e -> {
                      String resource = "parintitule/0/10/Oui/"+intitule.getText();
                      rechercheForm(marcheform,resource);
                
                    });
                container.add(intitule);
                container.add(b);
                Dialog.show("Recherche",container ,new Command("Annuler"));  
                
            }});
          
        marcheform.getToolbar().addCommandToOverflowMenu(new Command("Par categorie-ville",searchIcon){
            public void actionPerformed(ActionEvent evt){
                Container container = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                Picker productCategory = new Picker();
                productCategory.setStrings("Fruits","Legumes","Tubercules","Cereales");
                productCategory.setSelectedString("Fruits");
                Picker ville = new Picker();
                ville.setStrings("Ngaoundere","Belel","Mbe","Nganha","Nyambaka","Martap",
                              "Tignere","Mayo-Baleo","Kontcha",
                              "Banyo","Bankim","Mayo-Darle",
                              "Meiganga","Dir","Djohong","Ngaoui",
                              "Tibati","Ngaoundal",
                              "Nanga-Eboko","Bibey","Lembe","Mbandjock","Minta","Nkoteng","Sem",
                              "Monatele","Batchenga","Ebebda","Elig-Mfomo","Evodoula","Lobo","Monatele","Obala","Okola","Saa",
                              "Bafia","Bokito","Deuk","Kiiki","Kom-Yambetta","Makenene","Nitoukou","Ombessa",
                              "Ntui","Mbangassina","Ngambe-Tikar","Ngoro","Yoko",
                              "Mfou","Awae","Esse",
                              "Ngoumou","Akono","Bokok","Mbankomo",
                              "Yaounde",
                              "Eseka","Biyouha","Bot-Makak","Mbandjock","Dibang","Makak","Matomb","Messondo","Ngog-Mapubi","Nguibassal",
                              "Akonolinga","Ayos","Endom",
                              "Mbalmayo","Akoeman","Dzeng","Mengueme","Ngomedzap","Nkolmetet",
                              "Yokadouma","Gari-Gombo","Moloundou","Salapoumbe",
                              "Abong-mbang","Bebeng","Mbouanz","Dja","Dimako","Dimako","Doume","Doumaintang","Lomie","Messok","Messamena","Somalomo","Ngoyla","Nguelemendouka","Mboma",
                              "Batouri","Kette","Mbang","Ndelele",
                              "Bertoua","Belabo","Betare-Oya","Diang","Garoua-Boulai","Mandjou","Ngoura",
                              "Maroua","Bogo","Gazawa","Meri","Pette","Ndoukoula","Dargala",
                              "Kousseri","Blangoua","Darak","Fotokol","Goulfrey","Hile-Alifa","Logone-Birni","Makary","Waza","Zina",
                              "Yagoua","Datcheka","Gobo","Gueme","Guere","Kai-Kai","Kalfou","Kay-Hay","Maga","Tchati-Bali","Wina",
                              "Kaele","Guidiguis","Mindif","Meri","Moutourwa","Moulvoudaye","Pohri","Taibong",
                              "Mora","Kolofota","Tokombere",
                              "Mokolo","Bourrha","Hina","Koza","Mogode","Mayo-Maskota","Soulede-Roua",
                              "Nkongsamba","Bare-Bakem","Bonalea","Dibombari","Loum","Manjo","Mbanga","Melong","Njombe","Penja","Njongo","Nlonako",
                              "Yabassi","Nkondjock","Yingui","Nord-Makombe",
                              "Edea","Dizangue","Dibamba","Massok-Songloulou","Mouanko","Ndom","Ngambe","Ngwei","Nyanon","Pouma",
                              "Douala",
                              "Garoua","Bibemi","Dembo","Lagdo","Mayo-Hourra","Pitoa","Tcheboa","Demsa","Bascheo",
                              "Poli","Beka",
                              "Guider","Figuil","Mayo-Oulo",
                              "Tcholire","Rey-Bouba","Touboro",
                              "Fundong","Belo","Bum","Njinikom",
                              "Kumbo","Jakiri","Mbven","Nkum","Noni","Oku",
                              "Nkambe","Ako","Misaje","Ndu","Nwa",
                              "Wum","FunGom","Furu-Awa","Menchum-Valley",
                              "Bamenda","Bafut","Bali","Santa-Akum","Tuboro",
                              "Mbengwi","Batibo","Njikwa","Angie","Widikum-Menka",
                              "Ndop","Babessi","Bali-Kumbat",
                              "Mbouda","Babadjou","Batcham","Galim",
                              "Bafang","Bafou","Bana","Bafang","Bandja","Banka","Kekem","Banwa",
                              "Baham","Bamendjou","Bangou","Batie",
                              "Bandjoun","Bayagam","Poumougne",
                              "Dschang","Fokoue","Fongo-Tongo","Nkong-Ni","Penka-Michel","Santchou",
                              "Bafoussam","Baleng","Bamougoum",
                              "Bangante","Bazou","Bassamba","Tonga",
                              "Foumba","Bangourain","Foumbot","Kouoptamo","Koutaba","Magba","Malentouen","Massangam","Njimom",
                              "Sangmelima","Bengbis","Djoum","Meyomessala","Meyomessi","Mintom","Oveng","Sangmelima","Zoetele",
                              "Ebolowa","Biwong-Bane","Biwong-Bulu","Efoulan","Mengong","Mvangane","Ngoulemakong",
                              "Kribi","Akom-II","Bipindi","Campo","Niete","Lokundje","Lolodorf","Mvengue",
                              "Ambam","MAAN","Olamze","Kye-Ossi",
                              "Limbe","Buea","Muyuka","Tiko",
                              "Bangem","Tombel","Nguti",
                              "Menji","Alou","Fontem","Wabane",
                              "Mamfe","Akwaya","Eyumodjock","Upper-Bayang",
                              "Kumba","Konye","Mbongue",
                              "Mudemba","Bamuso","Ekondo-Titi","Idabato","Isanguele","Kombo-Abedimo","Kombo-Idinti","Mudemba");
                ville.setSelectedString("Banyo");
                Button b = new Button("Recherche");
                b.addActionListener(e -> {
                      String resource = "parcategorieville/0/10/Oui/"+productCategory.getSelectedString()+"/"+ville.getSelectedString();
                      rechercheForm(marcheform,resource);
                
                    });
                
                container.add(productCategory);
                container.add(ville);
                container.add(b);
                Dialog.show("Recherche",container ,new Command("Annuler"));  
                
            }});
          
        ClientProductInfiniteContainer pic = new ClientProductInfiniteContainer();
        marcheform.addComponent(BorderLayout.CENTER,pic.getProduct(ip,Placeholder,"0/10/Oui"));
        marcheform.show();
   }
   
   public void rechercheForm(Form form,String resource){
       Form rechercheform = new Form("Resultat Recherche",new BorderLayout());
       rechercheform.getToolbar().setBackCommand(new Command(""){
                              public void actionPerformed(ActionEvent evt){
                                form.showBack();  
                            }
                     });
       ClientProductInfiniteContainer pic = new ClientProductInfiniteContainer();
       rechercheform.addComponent(BorderLayout.CENTER,pic.getProduct(ip,Placeholder,resource));
       rechercheform.show();
   }
   
   
   public void showsupportscreen(){
          Form contactform = new Form("Support");
          contactform.setLayout(new BorderLayout());
          addMenuClient(contactform);
          Container layoutY = new Container(new BoxLayout(BoxLayout.Y_AXIS));
          
          Style s = UIManager.getInstance().getComponentStyle("Title");
          FontImage phoneIcon = FontImage.createMaterial(FontImage.MATERIAL_PHONE, s);
          FontImage emailIcon = FontImage.createMaterial(FontImage.MATERIAL_EMAIL, s);
          
          Button phone = new Button(Phone,phoneIcon);
           phone.addActionListener((e) -> {
            Display.getInstance().dial(PhoneNumber);
        });
          
           Button email = new Button(Email,emailIcon);
           email.addActionListener((e) -> {
            Message m = new Message("Saisir message ici:\n");
            Display.getInstance().sendMessage(new String[] {EmailValue}, "Contact from Eat", m);
        });
          
          layoutY.add(phone);
          layoutY.add(email);
          
          contactform.add(BorderLayout.CENTER,BorderLayout.centerAbsolute(layoutY));
          contactform.show();
    }
   
   public void showaproposscreen(){
        Form aproposform = new Form("A propos",new BoxLayout(BoxLayout.Y_AXIS));
        addMenuClient(aproposform);
        String[] messages = {
            "Eat est votre restaurant virtuel vous permettant de précommander vos repas du Lundi au Vendredi entre 9h et 11h30min.",
            "Notre service est ouvert du Lundi au Vendredi.\n Les précommandes sont passées uniquement depuis l'application smartphone entre 9h et 11h30min. Le paiement de vos commandes se fait à la livraison. Nous assurons gratuitement la livraison de vos commandes à  partir de midi",
            "Notre service est actuellement ouvert sur la ville de yaounde uniquement.",
            "Nous assurons gratuitement la livraison de vos commandes a partir de midi.",
            "Votre securité et satisfaction alimentaire démeure notre priorité."            
        };
       
        Label label0 = new Label("A propos de MHAgro");
        label0.setUIID("AproposLabel");
        SpanLabel message0 = new SpanLabel(messages[0], "Aproposspanlabel");
        
        Label label1 = new Label("Comment commander?");
        label1.setUIID("AproposLabel");
        SpanLabel message1 = new SpanLabel(messages[1], "Aproposspanlabel");
        
        Label label2 = new Label("Zone de livraison");
        label2.setUIID("AproposLabel");
        SpanLabel message2 = new SpanLabel(messages[2], "Aproposspanlabel");
        
        Label label3 = new Label("Mode de livraison");
        label3.setUIID("AproposLabel");
        SpanLabel message3 = new SpanLabel(messages[3], "Aproposspanlabel");
        
        Label label4 = new Label("Notre Slogan");
        label4.setUIID("AproposLabel");
        SpanLabel message4 = new SpanLabel(messages[4], "Aproposspanlabel");
        
        aproposform.add(label0);
        aproposform.add(message0);
        
        aproposform.add(label1);
        aproposform.add(message1);
        
        aproposform.add(label2);
        aproposform.add(message2);
        
        aproposform.add(label3);
        aproposform.add(message3);
        
        aproposform.add(label4);
        aproposform.add(message4);
        
        aproposform.show();
        
    }
   
   public void producteursForm(){
          Form producteursform = new Form("Producteurs");
          producteursform.setLayout(new BorderLayout());
          addMenuClient(producteursform);
          Container layoutY = new Container(new BoxLayout(BoxLayout.Y_AXIS));
          
          
          
          Button login = new Button("Connectez vous");
           login.addActionListener((e) -> {
               loginForm(producteursform);
        });
          
           Button registration = new Button("Creer votre compte");
           registration.addActionListener((e) -> {
            createproducteurForm(producteursform);
        });
          
          layoutY.add(login);
          layoutY.add(registration);
          
          producteursform.add(BorderLayout.CENTER,BorderLayout.centerAbsolute(layoutY));
          producteursform.show();
    }
   
   public void createproducteurForm(Form form){
       Form createproducteurform = new Form("Creer votre compte",new BoxLayout(BoxLayout.Y_AXIS));
       createproducteurform.getToolbar().setBackCommand(new Command(""){
                              public void actionPerformed(ActionEvent evt){
                                form.showBack();
                                
                            }
                     });
       
       Label  producteurIntituleLabel = new Label("Intitule","ProductCreateLabel");
       TextField producteurIntitule = new TextField();
       producteurIntitule.setConstraint(TextArea.ANY);
       
       
       Label  producteurMotdepasseLabel = new Label("Mot de passe","ProductCreateLabel");
       TextField producteurMotdepasse = new TextField();
       producteurMotdepasse.setConstraint(TextArea.PASSWORD);
       
       Label  producteurTelephoneLabel = new Label("Telephone","ProductCreateLabel");
       TextField producteurTelephone = new TextField();
       producteurTelephone.setConstraint(TextArea.PHONENUMBER);

       
       Label  producteurPaysLabel = new Label("Pays","ProductCreateLabel");
       Picker producteurPays = new Picker();
       producteurPays.setStrings("Cameroun");
       producteurPays.setSelectedString("Cameroun");
      
       
       Label  producteurRegionLabel = new Label("Region","ProductCreateLabel");
       Picker producteurRegion = new Picker();
       producteurRegion.setStrings("Adamaoua","Centre","Est","Extrême-Nord","Littoral","Nord","Nord-Ouest","Ouest","Sud","Sud-Ouest");
       producteurRegion.setSelectedString(" ");

       
       Label  producteurDepartementLabel = new Label("Departement","ProductCreateLabel");
       Picker producteurDepartement = new Picker();
       producteurDepartement.setStrings(" ");
       producteurDepartement.setSelectedString(" ");
       
       Label  producteurVilleLabel = new Label("Ville","ProductCreateLabel");
//       TextField producteurVille = new TextField();
       Picker producteurVille = new Picker();
       producteurVille.setStrings(" ");
       producteurVille.setSelectedString(" ");
       
        producteurRegion.addActionListener(e -> {                
           switch(producteurRegion.getSelectedString()) {
            case "Adamaoua":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Vina","Faro-Et-Deo","Mayo-Banyo","Mbere","Djerem");
                break;
            case "Centre":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Haute-Sanaga","Lekie","Mbam-Et-Inoubou","Mbam-Et-Kim","Mefou-Et-Afamba","Mefou-Et-Akono","Mfoundi","Nyong-Et-Kelle","Nyong-Et-Mfoumou","Nyomg-Et-Soo");
                break;
            case "Est":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Boumba-Et-Ngoko","Haut-Nyong","Kadey","Lom-Et-Djerem");
                break;
            case "Extrême-Nord":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Diamare","Logone-Et-Chari","Mayo-Danay","Mayo-Kani","Mayo-Sava","Mayo-Tsanaga");
                break;    
             case "Littoral":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Moungo","Nkam","Sanaga-Maritime","Wouri");
                break;
             case "Nord":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Benoue","Faro","Mayo-Louti","Mayo-Rey");
                break;    
            case "Nord-Ouest":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Boyo","Bui","Donga-Matung","Menchum","Mezam","Momo","Ngo-Ketunjia");
                break;       
            case "Ouest":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Bamboutos","Haut-Nkam","Hauts-Plateaux","Koung-Khi","Menoua","Mifi","Nde","Noun");
                break; 
            case "Sud":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Dja-Et-Lobo","Mvila","Ocean","Valee-Du-Ntem");
                break;
            case "Sud-Ouest":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Fako","Koupe-Manengouba","Lebialem","Manyu","Meme","Ndian");
                break;
           }
           producteurVille.setStrings(" ");
           producteurVille.setSelectedString(" ");
       });
       
       producteurDepartement.addActionListener(e -> {                
           switch(producteurDepartement.getSelectedString()) {
            case "Vina":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ngaoundere","Belel","Mbe","Nganha","Nyambaka","Martap");
                break;
            case "Faro-Et-Deo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Tignere","Mayo-Baleo","Kontcha");
                break;
            case "Mayo-Banyo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Banyo","Bankim","Mayo-Darle");
                break;
            case "Mbere":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Meiganga","Dir","Djohong","Ngaoui");
                break;
            case "Djerem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Tibati","Ngaoundal");
                break;
            case "Haute-Sanaga":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Nanga-Eboko","Bibey","Lembe","Mbandjock","Minta","Nkoteng","Sem");
                break;
            case "Lekie":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Monatele","Batchenga","Ebebda","Elig-Mfomo","Evodoula","Lobo","Monatele","Obala","Okola","Saa");
                break;
            case "Mbam-Et-Inoubou":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bafia","Bokito","Deuk","Kiiki","Kom-Yambetta","Makenene","Nitoukou","Ombessa");
                break;
            case "Mbam-Et-Kim":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ntui","Mbangassina","Ngambe-Tikar","Ngoro","Yoko");
                break;
            case "Mefou-Et-Afamba":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mfou","Awae","Esse");
                break;
            case "Mefou-Et-Akono":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ngoumou","Akono","Bokok","Mbankomo");
                break;
            case "Mfoundi":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yaounde");
                break;
            case "Nyong-Et-Kelle":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Eseka","Biyouha","Bot-Makak","Mbandjock","Dibang","Makak","Matomb","Messondo","Ngog-Mapubi","Nguibassal");
                break;
            case "Nyong-Et-Foumou":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Akonolinga","Ayos","Endom");
                break;
            case "Nyong-Et-Soo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mbalmayo","Akoeman","Dzeng","Mengueme","Ngomedzap","Nkolmetet");
                break;
            case "Boumba-Et-Ngoko":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yokadouma","Gari-Gombo","Moloundou","Salapoumbe");
                break;
            case "Haut-Nyong":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Abong-mbang","Bebeng","Mbouanz","Dja","Dimako","Dimako","Doume","Doumaintang","Lomie","Messok","Messamena","Somalomo","Ngoyla","Nguelemendouka","Mboma");
                break;   
            case "Kadey":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Batouri","Kette","Mbang","Ndelele");
                break;
            case "Lom-Et-Djerem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bertoua","Belabo","Betare-Oya","Diang","Garoua-Boulai","Mandjou","Ngoura");
                break;
          case "Diamare":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Maroua","Bogo","Gazawa","Meri","Pette","Ndoukoula","Dargala");
                break;
           case "Logone-Et-Chari":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kousseri","Blangoua","Darak","Fotokol","Goulfrey","Hile-Alifa","Logone-Birni","Makary","Waza","Zina");
                break;
           case "Mayo-Danay":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yagoua","Datcheka","Gobo","Gueme","Guere","Kai-Kai","Kalfou","Kay-Hay","Maga","Tchati-Bali","Wina");
                break;
            case "Mayo-Kani":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kaele","Guidiguis","Mindif","Meri","Moutourwa","Moulvoudaye","Pohri","Taibong");
                break;
            case "Mayo-Sava":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mora","Kolofota","Tokombere");
                break;
            case "Mayo-Tsanaga":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mokolo","Bourrha","Hina","Koza","Mogode","Mayo-Maskota","Soulede-Roua");
                break;
            case "Moungo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Nkongsamba","Bare-Bakem","Bonalea","Dibombari","Loum","Manjo","Mbanga","Melong","Njombe","Penja","Njongo","Nlonako");
                break;
            case "Nkam":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yabassi","Nkondjock","Yingui","Nord-Makombe");
                break;
            case "Sanaga-Maritime":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Edea","Dizangue","Dibamba","Massok-Songloulou","Mouanko","Ndom","Ngambe","Ngwei","Nyanon","Pouma");
                break;
            case "Wouri":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Douala");
                break;
            case "Benoue":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Garoua","Bibemi","Dembo","Lagdo","Mayo-Hourra","Pitoa","Tcheboa","Demsa","Bascheo");
                break;
            case "Faro":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Poli","Beka");
                break;
            case "Mayo-Louti":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Guider","Figuil","Mayo-Oulo");
                break;
            case "Mayo-Rey":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Tcholire","Rey-Bouba","Touboro");
                break;
            case "Boyo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Fundong","Belo","Bum","Njinikom");
                break;
             case "Bui":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kumbo","Jakiri","Mbven","Nkum","Noni","Oku");
                break;
            case "Donga-Matung":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Nkambe","Ako","Misaje","Ndu","Nwa");
                break;
            case "Menchum":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Wum","FunGom","Furu-Awa","Menchum-Valley");
                break;
            case "Mezam":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bamenda","Bafut","Bali","Santa-Akum","Tuboro");
                break;
           case "Momo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mbengwi","Batibo","Njikwa","Angie","Widikum-Menka");
                break;     
           case "Ngo-Ketunjia":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ndop","Babessi","Bali-Kumbat");
                break;           
            case "Bamboutos":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mbouda","Babadjou","Batcham","Galim");
                break;
            case "Haut-Nkam":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bafang","Bafou","Bana","Bafang","Bandja","Banka","Kekem","Banwa");
                break;
            case "Hauts-Plateaux":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Baham","Bamendjou","Bangou","Batie");
                break;
            case "Koung-Khi":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bandjoun","Bayagam","Poumougne");
                break;
            case "Menoua":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Dschang","Fokoue","Fongo-Tongo","Nkong-Ni","Penka-Michel","Santchou");
                break;
            case "Mifi":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bafoussam","Baleng","Bamougoum");
                break;
            case "Nde":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bangante","Bazou","Bassamba","Tonga");
                break;
            case "Noun":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Foumba","Bangourain","Foumbot","Kouoptamo","Koutaba","Magba","Malentouen","Massangam","Njimom");
                break;
            case "Dja-Et-Lobo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Sangmelima","Bengbis","Djoum","Meyomessala","Meyomessi","Mintom","Oveng","Sangmelima","Zoetele");
                break;
            case "Mvilla":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ebolowa","Biwong-Bane","Biwong-Bulu","Efoulan","Mengong","Mvangane","Ngoulemakong");
                break;
            case "Ocean":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kribi","Akom-II","Bipindi","Campo","Niete","Lokundje","Lolodorf","Mvengue");
                break;
            case "Valee-Du-Ntem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ambam","MAAN","Olamze","Kye-Ossi");
                break;
            case "Fako":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Limbe","Buea","Muyuka","Tiko");
                break;
            case "Koupe-Manengouba":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bangem","Tombel","Nguti");
                break;
            case "Lebialem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Menji","Alou","Fontem","Wabane");
                break;
            case "Manyu":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mamfe","Akwaya","Eyumodjock","Upper-Bayang");
                break;
            case "Meme":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kumba","Konye","Mbongue");
                break;
            case "Ndian":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mudemba","Bamuso","Ekondo-Titi","Idabato","Isanguele","Kombo-Abedimo","Kombo-Idinti","Mudemba");
                break;
           }
   
       });
       
       
       
       
       Button saveProducteurButton = new Button("Enregistrer");
       saveProducteurButton.addActionListener(e -> {
           
           if(producteurPays.getSelectedString() == " "){
                 Dialog.show("Info","selectionner pays","OK",null);
           }else{
               if(producteurRegion.getSelectedString() == " "){
                Dialog.show("Info","selectionner region","OK",null);
               }else{
                   if(producteurDepartement.getSelectedString() == " "){
                        Dialog.show("Info","selectionner departement","OK",null);
                   }else{
                       if(producteurVille.getSelectedString() == " "){
                        Dialog.show("Info","selectionner ville","OK",null);
                         }else{
                           JSONObject jo = new JSONObject();
                           String intitule = producteurIntitule.getText();
                           String telephone = producteurTelephone.getText();
                           String motdepasse = producteurMotdepasse.getText();
                           String pays = producteurPays.getSelectedString();
                           String region = producteurRegion.getSelectedString();
                           String departement = producteurDepartement.getSelectedString();
                           String ville = producteurVille.getSelectedString();
                           try {
                               
                               jo.put("intitule",intitule);
                               jo.put("telephone",telephone);
                               jo.put("motdepasse",motdepasse);
                               jo.put("pays",pays);
                               jo.put("region",region);
                               jo.put("departement",departement);
                               jo.put("ville",ville);
                               
                               MHAgroClient maclient = new MHAgroClient(ip,"vendeurregistrationapi/registration/");
                               Map map = maclient.registration(jo);
                               
                               String etat = (String) map.get("etat");
                               String description = (String) map.get("description");
                               
                               if(etat.equals("exist")){
                                  Dialog.show("Infos",description,"OK",null);
                                 }
                               if(etat.equals("erreur")){
                                  Dialog.show("Infos",description,"OK",null);
                                 }
                               if(etat.equals("succes")){
                                    Dialog.show("Infos",description,"OK",null);
                                    loginForm(form);
                                 }
                               
                             } catch (JSONException ex) {
                           } catch (IOException ex) {
                           }
            

                         
                   }
                       
                   }
               }
           }    
            });
//       String pattern = "\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}";
       String pattern = "\\d{9}";
       Validator validator = new Validator();
                  validator.setShowErrorMessageForFocusedComponent(true);
                  validator.setValidationFailureHighlightMode(Validator.HighlightMode.UIID);
                  validator.setErrorMessageUIID("ProductValidationLabel");
                  
        validator.addConstraint(producteurIntitule,new  LengthConstraint(1,"Ce champ est obligatoire")).
                  addConstraint(producteurTelephone,new LengthConstraint(1,"Ce champ est obligatoire")). 
                  addConstraint(producteurTelephone,new RegexConstraint(pattern, "Ce numero n'est pas valide")). 
                  addConstraint(producteurMotdepasse,new LengthConstraint(1,"Ce champ est obligatoire"));
        validator.addSubmitButtons(saveProducteurButton);
        
        
        
       
       createproducteurform.add(producteurIntituleLabel);
       createproducteurform.add(producteurIntitule);
       createproducteurform.add(producteurTelephoneLabel);
       createproducteurform.add(producteurTelephone);
        createproducteurform.add(producteurMotdepasseLabel);
       createproducteurform.add(producteurMotdepasse);
       createproducteurform.add(producteurPaysLabel);
       createproducteurform.add(producteurPays);
       createproducteurform.add(producteurRegionLabel);
       createproducteurform.add(producteurRegion);
       createproducteurform.add(producteurDepartementLabel);
       createproducteurform.add(producteurDepartement);
       createproducteurform.add(producteurVilleLabel);
       createproducteurform.add(producteurVille);
       createproducteurform.add(saveProducteurButton);

       
       createproducteurform.show();
   }
  
   void loginForm(Form form){
        
        Form loginForm = new Form("Connexion");
        loginForm.setLayout(new BorderLayout());
        
         loginForm.getToolbar().setBackCommand(new Command(""){
                              public void actionPerformed(ActionEvent evt){
                                form.showBack();           
                            }
                     });
        
        BorderLayout centerLayout = new BorderLayout();
        centerLayout.setCenterBehavior(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE);               
        Container centerContainer = new Container(centerLayout);
                  
        Container registrationContainer = new Container(new BorderLayout());

        Container componentContainer = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                  componentContainer.setScrollableY(true);
                  componentContainer.setScrollVisible(false);
                  
        
        TextField telephone = new TextField("", "Telephone", 20, TextField.PHONENUMBER);
        FontImage.setMaterialIcon(telephone.getHintLabel(), FontImage.MATERIAL_PHONE);
        
        TextField password = new TextField("", "Mot de passe", 20, TextField.PASSWORD);
        FontImage.setMaterialIcon(password.getHintLabel(), FontImage.MATERIAL_LOCK);
        
        Button save = new Button("Connexion");
        Button registration = new Button("Mot de passe oublie");
        
        
        componentContainer.addComponent(new Label("Telephone","ProductCreateLabel"));
        componentContainer.addComponent(telephone);
        componentContainer.addComponent(new Label("Mot de passe","ProductCreateLabel"));
        componentContainer.addComponent(password);
        componentContainer.addComponent(save);
        componentContainer.addComponent(registration);
        
        save.addActionListener(e -> {               
                 JSONObject jo = new JSONObject();
                 String phone = telephone.getText();
                 String motdepasse = password.getText();   
                 try {
                      jo.put("telephone",phone);
                      jo.put("motdepasse",motdepasse);
                      MHAgroClient maclient = new MHAgroClient(ip,"vendeurloginapi/login/");
                               Map map = maclient.registration(jo);
                               String etat = (String) map.get("etat");
                               String description = (String) map.get("description");
                               
                               if(etat.equals("loginError")){
                                  Dialog.show("Infos",description,"OK",null);
                                 }
                               if(etat.equals("erreur")){
                                  Dialog.show("Infos",description,"OK",null);
                                 }
                               if(etat.equals("succes")){
    
                                  String id = (String) map.get("id");
                                  String intitule = (String) map.get("intitule");
                                  String vendeurphone = (String) map.get("telephone");
                                  String pays = (String) map.get("pays");
                                  String region = (String) map.get("region");
                                  String departement = (String)map.get("departement");
                                  String ville = (String) map.get("ville");
                                  
                                  vendeur = new Vendeur();
                                  vendeur.setId(id);
                                  vendeur.setIntitule(intitule);
                                  vendeur.setTelephone(vendeurphone);
                                  vendeur.setPays(pays);
                                  vendeur.setRegion(region);
                                  vendeur.setDepartement(departement);
                                  vendeur.setVille(ville);
                                  Dialog.show("Infos",description,"OK",null);
                                  myproductlistForm(vendeur);
                                 }
                               if(etat.equals("desactive")){
                                  Dialog.show("Infos",description,"OK",null);
                                 }
                               
                               } catch (JSONException ex) {
                           } catch (IOException ex) { 
                   }
            
         });
        registration.addActionListener(e -> {
                 
        });
        Validator validator = new Validator();
                  validator.setShowErrorMessageForFocusedComponent(true);
                  validator.setValidationFailureHighlightMode(Validator.HighlightMode.UIID);
                  validator.setErrorMessageUIID("ProductValidationLabel");
        validator.addConstraint(telephone, new LengthConstraint(1,"Obligatoire")).               
                  addConstraint(password,new LengthConstraint(1,"Obligatoire"));
        
        validator.addSubmitButtons(save);
        registrationContainer.add(BorderLayout.CENTER,componentContainer);
        centerContainer.add(BorderLayout.CENTER,registrationContainer);
        loginForm.addComponent(BorderLayout.CENTER,centerContainer);
        loginForm.show();
    }
   
   public void editproducteurForm(Vendeur vendeur){
       Form editproducteurform = new Form("Mise a jour profile",new BoxLayout(BoxLayout.Y_AXIS));
       addMenu(editproducteurform);
       Label  producteurIntituleLabel = new Label("Intitule","ProductCreateLabel");
       TextField producteurIntitule = new TextField();
       producteurIntitule.setConstraint(TextArea.ANY);
       producteurIntitule.setText(vendeur.getIntitule());
       
       
       Label  producteurMotdepasseLabel = new Label("Mot de passe","ProductCreateLabel");
       TextField producteurMotdepasse = new TextField();
       producteurMotdepasse.setConstraint(TextArea.PASSWORD);
       
       Label  producteurTelephoneLabel = new Label("Telephone","ProductCreateLabel");
       TextField producteurTelephone = new TextField();
       producteurTelephone.setConstraint(TextArea.PHONENUMBER);
       producteurTelephone.setText(vendeur.getTelephone());
       producteurTelephone.setEnabled(false);
              producteurTelephone.setEditable(false);


       
       Label  producteurPaysLabel = new Label("Pays","ProductCreateLabel");
       Picker producteurPays = new Picker();
       producteurPays.setStrings("Cameroun");
       producteurPays.setSelectedString("Cameroun");
       producteurPays.setText(vendeur.getPays());
       
       Label  producteurRegionLabel = new Label("Region","ProductCreateLabel");
       Picker producteurRegion = new Picker();
       producteurRegion.setStrings("Adamaoua","Centre","Est","Extrême-Nord","Littoral","Nord","Nord-Ouest","Ouest","Sud","Sud-Ouest");
       producteurRegion.setSelectedString(vendeur.getRegion());

       
       Label  producteurDepartementLabel = new Label("Departement","ProductCreateLabel");
       Picker producteurDepartement = new Picker();
       producteurDepartement.setStrings(" ");
       producteurDepartement.setSelectedString(vendeur.getDepartement());
       
       Label  producteurVilleLabel = new Label("Ville","ProductCreateLabel");
//       TextField producteurVille = new TextField();
       Picker producteurVille = new Picker();
       producteurVille.setStrings(" ");
       producteurVille.setSelectedString(vendeur.getVille());
       
        producteurRegion.addActionListener(e -> {                
           switch(producteurRegion.getSelectedString()) {
            case "Adamaoua":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Vina","Faro-Et-Deo","Mayo-Banyo","Mbere","Djerem");
                break;
            case "Centre":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Haute-Sanaga","Lekie","Mbam-Et-Inoubou","Mbam-Et-Kim","Mefou-Et-Afamba","Mefou-Et-Akono","Mfoundi","Nyong-Et-Kelle","Nyong-Et-Mfoumou","Nyomg-Et-Soo");
                break;
            case "Est":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Boumba-Et-Ngoko","Haut-Nyong","Kadey","Lom-Et-Djerem");
                break;
            case "Extrême-Nord":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Diamare","Logone-Et-Chari","Mayo-Danay","Mayo-Kani","Mayo-Sava","Mayo-Tsanaga");
                break;    
             case "Littoral":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Moungo","Nkam","Sanaga-Maritime","Wouri");
                break;
             case "Nord":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Benoue","Faro","Mayo-Louti","Mayo-Rey");
                break;    
            case "Nord-Ouest":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Boyo","Bui","Donga-Matung","Menchum","Mezam","Momo","Ngo-Ketunjia");
                break;       
            case "Ouest":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Bamboutos","Haut-Nkam","Hauts-Plateaux","Koung-Khi","Menoua","Mifi","Nde","Noun");
                break; 
            case "Sud":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Dja-Et-Lobo","Mvila","Ocean","Valee-Du-Ntem");
                break;
            case "Sud-Ouest":
                producteurDepartement.setSelectedString(" ");
                producteurDepartement.setStrings("Fako","Koupe-Manengouba","Lebialem","Manyu","Meme","Ndian");
                break;
           }
           producteurVille.setStrings(" ");
           producteurVille.setSelectedString(" ");
       });
       
       producteurDepartement.addActionListener(e -> {                
           switch(producteurDepartement.getSelectedString()) {
            case "Vina":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ngaoundere","Belel","Mbe","Nganha","Nyambaka","Martap");
                break;
            case "Faro-Et-Deo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Tignere","Mayo-Baleo","Kontcha");
                break;
            case "Mayo-Banyo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Banyo","Bankim","Mayo-Darle");
                break;
            case "Mbere":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Meiganga","Dir","Djohong","Ngaoui");
                break;
            case "Djerem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Tibati","Ngaoundal");
                break;
            case "Haute-Sanaga":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Nanga-Eboko","Bibey","Lembe","Mbandjock","Minta","Nkoteng","Sem");
                break;
            case "Lekie":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Monatele","Batchenga","Ebebda","Elig-Mfomo","Evodoula","Lobo","Monatele","Obala","Okola","Saa");
                break;
            case "Mbam-Et-Inoubou":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bafia","Bokito","Deuk","Kiiki","Kom-Yambetta","Makenene","Nitoukou","Ombessa");
                break;
            case "Mbam-Et-Kim":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ntui","Mbangassina","Ngambe-Tikar","Ngoro","Yoko");
                break;
            case "Mefou-Et-Afamba":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mfou","Awae","Esse");
                break;
            case "Mefou-Et-Akono":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ngoumou","Akono","Bokok","Mbankomo");
                break;
            case "Mfoundi":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yaounde");
                break;
            case "Nyong-Et-Kelle":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Eseka","Biyouha","Bot-Makak","Mbandjock","Dibang","Makak","Matomb","Messondo","Ngog-Mapubi","Nguibassal");
                break;
            case "Nyong-Et-Foumou":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Akonolinga","Ayos","Endom");
                break;
            case "Nyong-Et-Soo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mbalmayo","Akoeman","Dzeng","Mengueme","Ngomedzap","Nkolmetet");
                break;
            case "Boumba-Et-Ngoko":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yokadouma","Gari-Gombo","Moloundou","Salapoumbe");
                break;
            case "Haut-Nyong":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Abong-mbang","Bebeng","Mbouanz","Dja","Dimako","Dimako","Doume","Doumaintang","Lomie","Messok","Messamena","Somalomo","Ngoyla","Nguelemendouka","Mboma");
                break;   
            case "Kadey":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Batouri","Kette","Mbang","Ndelele");
                break;
            case "Lom-Et-Djerem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bertoua","Belabo","Betare-Oya","Diang","Garoua-Boulai","Mandjou","Ngoura");
                break;
          case "Diamare":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Maroua","Bogo","Gazawa","Meri","Pette","Ndoukoula","Dargala");
                break;
           case "Logone-Et-Chari":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kousseri","Blangoua","Darak","Fotokol","Goulfrey","Hile-Alifa","Logone-Birni","Makary","Waza","Zina");
                break;
           case "Mayo-Danay":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yagoua","Datcheka","Gobo","Gueme","Guere","Kai-Kai","Kalfou","Kay-Hay","Maga","Tchati-Bali","Wina");
                break;
            case "Mayo-Kani":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kaele","Guidiguis","Mindif","Meri","Moutourwa","Moulvoudaye","Pohri","Taibong");
                break;
            case "Mayo-Sava":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mora","Kolofota","Tokombere");
                break;
            case "Mayo-Tsanaga":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mokolo","Bourrha","Hina","Koza","Mogode","Mayo-Maskota","Soulede-Roua");
                break;
            case "Moungo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Nkongsamba","Bare-Bakem","Bonalea","Dibombari","Loum","Manjo","Mbanga","Melong","Njombe","Penja","Njongo","Nlonako");
                break;
            case "Nkam":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Yabassi","Nkondjock","Yingui","Nord-Makombe");
                break;
            case "Sanaga-Maritime":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Edea","Dizangue","Dibamba","Massok-Songloulou","Mouanko","Ndom","Ngambe","Ngwei","Nyanon","Pouma");
                break;
            case "Wouri":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Douala");
                break;
            case "Benoue":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Garoua","Bibemi","Dembo","Lagdo","Mayo-Hourra","Pitoa","Tcheboa","Demsa","Bascheo");
                break;
            case "Faro":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Poli","Beka");
                break;
            case "Mayo-Louti":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Guider","Figuil","Mayo-Oulo");
                break;
            case "Mayo-Rey":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Tcholire","Rey-Bouba","Touboro");
                break;
            case "Boyo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Fundong","Belo","Bum","Njinikom");
                break;
             case "Bui":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kumbo","Jakiri","Mbven","Nkum","Noni","Oku");
                break;
            case "Donga-Matung":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Nkambe","Ako","Misaje","Ndu","Nwa");
                break;
            case "Menchum":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Wum","FunGom","Furu-Awa","Menchum-Valley");
                break;
            case "Mezam":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bamenda","Bafut","Bali","Santa-Akum","Tuboro");
                break;
           case "Momo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mbengwi","Batibo","Njikwa","Angie","Widikum-Menka");
                break;     
           case "Ngo-Ketunjia":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ndop","Babessi","Bali-Kumbat");
                break;           
            case "Bamboutos":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mbouda","Babadjou","Batcham","Galim");
                break;
            case "Haut-Nkam":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bafang","Bafou","Bana","Bafang","Bandja","Banka","Kekem","Banwa");
                break;
            case "Hauts-Plateaux":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Baham","Bamendjou","Bangou","Batie");
                break;
            case "Koung-Khi":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bandjoun","Bayagam","Poumougne");
                break;
            case "Menoua":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Dschang","Fokoue","Fongo-Tongo","Nkong-Ni","Penka-Michel","Santchou");
                break;
            case "Mifi":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bafoussam","Baleng","Bamougoum");
                break;
            case "Nde":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bangante","Bazou","Bassamba","Tonga");
                break;
            case "Noun":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Foumba","Bangourain","Foumbot","Kouoptamo","Koutaba","Magba","Malentouen","Massangam","Njimom");
                break;
            case "Dja-Et-Lobo":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Sangmelima","Bengbis","Djoum","Meyomessala","Meyomessi","Mintom","Oveng","Sangmelima","Zoetele");
                break;
            case "Mvilla":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ebolowa","Biwong-Bane","Biwong-Bulu","Efoulan","Mengong","Mvangane","Ngoulemakong");
                break;
            case "Ocean":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kribi","Akom-II","Bipindi","Campo","Niete","Lokundje","Lolodorf","Mvengue");
                break;
            case "Valee-Du-Ntem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Ambam","MAAN","Olamze","Kye-Ossi");
                break;
            case "Fako":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Limbe","Buea","Muyuka","Tiko");
                break;
            case "Koupe-Manengouba":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Bangem","Tombel","Nguti");
                break;
            case "Lebialem":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Menji","Alou","Fontem","Wabane");
                break;
            case "Manyu":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mamfe","Akwaya","Eyumodjock","Upper-Bayang");
                break;
            case "Meme":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Kumba","Konye","Mbongue");
                break;
            case "Ndian":
                producteurVille.setSelectedString(" ");
                producteurVille.setStrings("Mudemba","Bamuso","Ekondo-Titi","Idabato","Isanguele","Kombo-Abedimo","Kombo-Idinti","Mudemba");
                break;
           }
   
       });
       
       
       
       
       Button saveProducteurButton = new Button("Enregistrer");
       saveProducteurButton.addActionListener(e -> {
           
           if(producteurPays.getSelectedString() == " "){
                 Dialog.show("Info","selectionner pays","OK",null);
           }else{
               if(producteurRegion.getSelectedString() == " "){
                Dialog.show("Info","selectionner region","OK",null);
               }else{
                   if(producteurDepartement.getSelectedString() == " "){
                        Dialog.show("Info","selectionner departement","OK",null);
                   }else{
                       if(producteurVille.getSelectedString() == " "){
                        Dialog.show("Info","selectionner ville","OK",null);
                         }else{
                           JSONObject jo = new JSONObject();
                           String intitule = producteurIntitule.getText();
                           String telephone = producteurTelephone.getText();
                           String motdepasse = producteurMotdepasse.getText();
                           String pays = producteurPays.getSelectedString();
                           String region = producteurRegion.getSelectedString();
                           String departement = producteurDepartement.getSelectedString();
                           String ville = producteurVille.getSelectedString();
                           String vendeurId = vendeur.getId() ;
                           try {
                               jo.put("vendeurId", vendeurId);
                               jo.put("intitule",intitule);
                               jo.put("telephone",telephone);
                               jo.put("motdepasse",motdepasse);
                               jo.put("pays",pays);
                               jo.put("region",region);
                               jo.put("departement",departement);
                               jo.put("ville",ville);
                          if( Dialog.show("Info", "Voulez-vous enregister les modifications","OK", "Cancel")){
                              MHAgroClient maclient = new MHAgroClient(ip,"vendeureditionapi/edition/");
                               Map map = maclient.registration(jo);
                               
                               String etat = (String) map.get("etat");
                               String description = (String) map.get("description");
                               
                               
                               if(etat.equals("erreur")){
                                  Dialog.show("Infos",description,"OK",null);
                                 }
                               if(etat.equals("succes")){
                                   
                                 String vId = (String) map.get("id");
                                 String vIntitule = (String)map.get("intitule");
                                 String vTelephone = (String)map.get("telephone");
                                 String vPays = (String)map.get("pays");
                                 String vRegion = (String)map.get("region");
                                 String vDepartement = (String)map.get("departement");
                                 String vVille = (String)map.get("ville");

                                 vendeur.setId(vId);
                                 vendeur.setIntitule(vIntitule);
                                 vendeur.setTelephone(vTelephone);
                                 vendeur.setPays(vPays);
                                 vendeur.setRegion(vRegion);
                                 vendeur.setDepartement(vDepartement);
                                 vendeur.setVille(vVille);
                                 
                                 Dialog.show("Infos",description,"OK",null);
                                 }     
                            }
                               
                               
                             } catch (JSONException ex) {
                           } catch (IOException ex) {
                           }
            

                         
                   }
                       
                   }
               }
           }    
            });
//       String pattern = "\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}";
       String pattern = "\\d{9}";
       Validator validator = new Validator();
                  validator.setShowErrorMessageForFocusedComponent(true);
                  validator.setValidationFailureHighlightMode(Validator.HighlightMode.UIID);
                  validator.setErrorMessageUIID("ProductValidationLabel");
                  
        validator.addConstraint(producteurIntitule,new  LengthConstraint(1,"Ce champ est obligatoire")).
                  addConstraint(producteurTelephone,new LengthConstraint(1,"Ce champ est obligatoire")). 
                  addConstraint(producteurTelephone,new RegexConstraint(pattern, "Ce numero n'est pas valide")). 
                  addConstraint(producteurMotdepasse,new LengthConstraint(1,"Ce champ est obligatoire"));
        validator.addSubmitButtons(saveProducteurButton);
        
        
        
       
       editproducteurform.add(producteurIntituleLabel);
       editproducteurform.add(producteurIntitule);
       editproducteurform.add(producteurTelephoneLabel);
       editproducteurform.add(producteurTelephone);
       editproducteurform.add(producteurMotdepasseLabel);
       editproducteurform.add(producteurMotdepasse);
       editproducteurform.add(producteurPaysLabel);
       editproducteurform.add(producteurPays);
       editproducteurform.add(producteurRegionLabel);
       editproducteurform.add(producteurRegion);
       editproducteurform.add(producteurDepartementLabel);
       editproducteurform.add(producteurDepartement);
       editproducteurform.add(producteurVilleLabel);
       editproducteurform.add(producteurVille);
       editproducteurform.add(saveProducteurButton);

       
       editproducteurform.show();
   }
 
}
